version: "3.3"

services:
  codesearch:
    container_name: codeSearch_Dev
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - "/usr/src/app/node_modules"
    environment:
      - NODE_ENV=dev
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - db_mongo
    links:
      - db_mongo
    ports:
      - 8080:8080
    stdin_open: true
    tty: true

  db_mongo:
    image: mongo:4.2.0
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
